// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6L2OCE9yspEd-mVNT4IP5DWZ7vm3zYBY',
    appId: '1:16318700827:web:351466b446308c626d87be',
    messagingSenderId: '16318700827',
    projectId: 'novamart-8be0a',
    authDomain: 'novamart-8be0a.firebaseapp.com',
    storageBucket: 'novamart-8be0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg18cB8rSasapbms0lYC80EfBXYmLXfhg',
    appId: '1:16318700827:android:088acea8c6964fb56d87be',
    messagingSenderId: '16318700827',
    projectId: 'novamart-8be0a',
    storageBucket: 'novamart-8be0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0jSbey2lc8853DDPig9TmJBW2NHdDhM',
    appId: '1:16318700827:ios:97760930b9a1bca96d87be',
    messagingSenderId: '16318700827',
    projectId: 'novamart-8be0a',
    storageBucket: 'novamart-8be0a.firebasestorage.app',
    iosBundleId: 'com.example.novamart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0jSbey2lc8853DDPig9TmJBW2NHdDhM',
    appId: '1:16318700827:ios:97760930b9a1bca96d87be',
    messagingSenderId: '16318700827',
    projectId: 'novamart-8be0a',
    storageBucket: 'novamart-8be0a.firebasestorage.app',
    iosBundleId: 'com.example.novamart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6L2OCE9yspEd-mVNT4IP5DWZ7vm3zYBY',
    appId: '1:16318700827:web:498464086c54376b6d87be',
    messagingSenderId: '16318700827',
    projectId: 'novamart-8be0a',
    authDomain: 'novamart-8be0a.firebaseapp.com',
    storageBucket: 'novamart-8be0a.firebasestorage.app',
  );
}
